DROP TABLE commente CASCADE CONSTRAINTS;
DROP TABLE note CASCADE CONSTRAINTS;

DROP TABLE image CASCADE CONSTRAINTS;

DROP TABLE post CASCADE CONSTRAINTS;

DROP TABLE utilisateur CASCADE CONSTRAINTS;
